# Generated by Django 5.2.16 on 2026-07-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종결 시각'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='contact_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='연락 완료 시각'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='first_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 확인 시각'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='first_viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_viewed_consultations', to=settings.AUTH_USER_MODEL, verbose_name='최초 확인자'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('new', '신규 접수'), ('acknowledged', '접수 확인'), ('assigned', '담당자 배정'), ('in_progress', '연락 중'), ('completed', '상담 완료'), ('waiting', '입소 대기'), ('closed', '종결')], default='new', max_length=20, verbose_name='진행 상태'),
        ),
        migrations.CreateModel(
            name='ConsultationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='지정 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='지정 시각')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='지정자')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_assignment_history', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='consultations.consultation', verbose_name='상담')),
            ],
            options={
                'verbose_name': '상담 담당자 지정',
                'verbose_name_plural': '상담 담당자 지정 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('viewed', '상담 열람'), ('acknowledged', '접수 확인'), ('assigned', '담당자 지정'), ('status_changed', '상태 변경'), ('note_updated', '상담 메모 변경'), ('contact_completed', '연락 완료'), ('closed', '상담 종결')], max_length=30, verbose_name='처리 내용')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='변경 전 상태')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='변경 후 상태')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='기록 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='처리 시각')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_status_events', to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='consultations.consultation', verbose_name='상담')),
            ],
            options={
                'verbose_name': '상담 처리 이력',
                'verbose_name_plural': '상담 처리 이력',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation', '-created_at'], name='consult_history_created_idx')],
            },
        ),
    ]
