# Generated by Django 5.2.16 on 2026-07-18 03:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text="기존 연도를 연 뒤 '새 항목으로 저장'을 사용하면 다음 연도 자료를 쉽게 만들 수 있습니다.", unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='기준연도')),
                ('effective_date', models.DateField(verbose_name='적용 시작일')),
                ('is_published', models.BooleanField(default=False, help_text='선택한 자료만 홈페이지 계산기의 연도 목록에 표시됩니다.', verbose_name='홈페이지 공개')),
                ('source_note', models.TextField(blank=True, help_text='공단 고시명, 확인일 또는 내부 검토 내용을 기록해 주세요.', verbose_name='근거·확인 메모')),
                ('meal_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='식사 1끼')),
                ('snack_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='간식 1회')),
                ('facility_standard_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='시설 일반 본인부담률(%)')),
                ('facility_discount40_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='시설 40% 감경 본인부담률(%)')),
                ('facility_discount60_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='시설 60% 감경 본인부담률(%)')),
                ('home_standard_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='재가 일반 본인부담률(%)')),
                ('home_discount40_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='재가 40% 감경 본인부담률(%)')),
                ('home_discount60_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='재가 60% 감경 본인부담률(%)')),
                ('home_limit_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='1등급 월 한도액')),
                ('home_limit_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='2등급 월 한도액')),
                ('home_limit_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3등급 월 한도액')),
                ('home_limit_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='4등급 월 한도액')),
                ('home_limit_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='5등급 월 한도액')),
                ('facility_rate_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시설 1등급 1일 수가')),
                ('facility_rate_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시설 2등급 1일 수가')),
                ('facility_rate_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시설 3등급 1일 수가')),
                ('facility_rate_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시설 4등급 1일 수가')),
                ('facility_rate_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='시설 5등급 1일 수가')),
                ('daycare_3_6_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3~6시간 1등급')),
                ('daycare_3_6_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3~6시간 2등급')),
                ('daycare_3_6_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3~6시간 3등급')),
                ('daycare_3_6_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3~6시간 4등급')),
                ('daycare_3_6_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='3~6시간 5등급')),
                ('daycare_6_8_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='6~8시간 1등급')),
                ('daycare_6_8_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='6~8시간 2등급')),
                ('daycare_6_8_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='6~8시간 3등급')),
                ('daycare_6_8_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='6~8시간 4등급')),
                ('daycare_6_8_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='6~8시간 5등급')),
                ('daycare_8_10_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='8~10시간 1등급')),
                ('daycare_8_10_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='8~10시간 2등급')),
                ('daycare_8_10_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='8~10시간 3등급')),
                ('daycare_8_10_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='8~10시간 4등급')),
                ('daycare_8_10_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='8~10시간 5등급')),
                ('daycare_10_13_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='10~13시간 1등급')),
                ('daycare_10_13_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='10~13시간 2등급')),
                ('daycare_10_13_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='10~13시간 3등급')),
                ('daycare_10_13_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='10~13시간 4등급')),
                ('daycare_10_13_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='10~13시간 5등급')),
                ('daycare_13_plus_1', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='13시간 초과 1등급')),
                ('daycare_13_plus_2', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='13시간 초과 2등급')),
                ('daycare_13_plus_3', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='13시간 초과 3등급')),
                ('daycare_13_plus_4', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='13시간 초과 4등급')),
                ('daycare_13_plus_5', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='13시간 초과 5등급')),
                ('visit_30', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 30분')),
                ('visit_60', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 60분')),
                ('visit_90', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 90분')),
                ('visit_120', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 120분')),
                ('visit_150', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 150분')),
                ('visit_180', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 180분')),
                ('visit_210', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 210분')),
                ('visit_240', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='방문요양 240분')),
                ('regular_care_hourly_pay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='일반요양 시급')),
                ('family60_hourly_pay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='가족요양 60분 시급')),
                ('family90_hourly_pay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='가족요양 90분 시급')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '연도별 급여비용 설정',
                'verbose_name_plural': '연도별 급여비용 설정',
                'ordering': ['-year'],
            },
        ),
    ]
