# Generated by Django 5.2.16 on 2026-07-18 03:05

from datetime import date

from django.db import migrations


def seed_2026_schedule(apps, schema_editor):
    BenefitSchedule = apps.get_model("benefits", "BenefitSchedule")
    BenefitSchedule.objects.update_or_create(
        year=2026,
        defaults={
            "effective_date": date(2026, 1, 1),
            "is_published": True,
            "source_note": "기존 2026년 홈페이지 계산기 기준값입니다. 공단 고시 원문과 기관 비급여 기준을 최종 확인해 주세요.",
            "meal_price": 3500,
            "snack_price": 1000,
            "facility_standard_percent": "20.00",
            "facility_discount40_percent": "12.00",
            "facility_discount60_percent": "8.00",
            "home_standard_percent": "15.00",
            "home_discount40_percent": "9.00",
            "home_discount60_percent": "6.00",
            "home_limit_1": 2512900,
            "home_limit_2": 2331200,
            "home_limit_3": 1528200,
            "home_limit_4": 1409700,
            "home_limit_5": 1208900,
            "facility_rate_1": 93070,
            "facility_rate_2": 86340,
            "facility_rate_3": 81540,
            "facility_rate_4": 81540,
            "facility_rate_5": 81540,
            "daycare_3_6_1": 41820,
            "daycare_3_6_2": 38720,
            "daycare_3_6_3": 35740,
            "daycare_3_6_4": 34120,
            "daycare_3_6_5": 32490,
            "daycare_6_8_1": 56060,
            "daycare_6_8_2": 51930,
            "daycare_6_8_3": 47940,
            "daycare_6_8_4": 46300,
            "daycare_6_8_5": 44650,
            "daycare_8_10_1": 69730,
            "daycare_8_10_2": 64590,
            "daycare_8_10_3": 59640,
            "daycare_8_10_4": 58010,
            "daycare_8_10_5": 56360,
            "daycare_10_13_1": 76820,
            "daycare_10_13_2": 71160,
            "daycare_10_13_3": 65750,
            "daycare_10_13_4": 64090,
            "daycare_10_13_5": 62460,
            "daycare_13_plus_1": 82370,
            "daycare_13_plus_2": 76310,
            "daycare_13_plus_3": 70500,
            "daycare_13_plus_4": 68860,
            "daycare_13_plus_5": 67240,
            "visit_30": 17450,
            "visit_60": 25320,
            "visit_90": 34120,
            "visit_120": 43430,
            "visit_150": 50640,
            "visit_180": 57020,
            "visit_210": 63530,
            "visit_240": 70080,
            "regular_care_hourly_pay": 14000,
            "family60_hourly_pay": 21000,
            "family90_hourly_pay": 19000,
        },
    )


def remove_2026_schedule(apps, schema_editor):
    BenefitSchedule = apps.get_model("benefits", "BenefitSchedule")
    BenefitSchedule.objects.filter(year=2026).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_2026_schedule, remove_2026_schedule),
    ]
