# Generated by Django 5.2.16 on 2026-07-18 07:37

import django.db.models.deletion
import django.utils.timezone
import staff_notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0002_consultation_assigned_to_consultation_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('first_reminder_minutes', models.PositiveIntegerField(default=20, verbose_name='1차 재알림(분)')),
                ('second_reminder_minutes', models.PositiveIntegerField(default=60, verbose_name='2차 재알림(분)')),
                ('max_reminders', models.PositiveSmallIntegerField(default=2, verbose_name='최대 재알림 횟수')),
                ('max_delivery_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='최대 발송 시도 횟수')),
                ('worker_poll_seconds', models.PositiveSmallIntegerField(default=10, verbose_name='작업 확인 간격(초)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '알림 운영 설정',
                'verbose_name_plural': '알림 운영 설정',
            },
        ),
        migrations.CreateModel(
            name='StaffNotificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='직원 이름')),
                ('role_title', models.CharField(blank=True, max_length=80, verbose_name='직책')),
                ('service_scope', models.CharField(choices=[('all', '전체'), ('nursing_home', '요양원'), ('day_care', '주간보호'), ('home_care', '방문요양')], default='all', max_length=20, verbose_name='소속 급여종별')),
                ('consultation_types', models.JSONField(default=staff_notifications.models.default_consultation_types, verbose_name='알림 수신 상담 유형')),
                ('web_push_enabled', models.BooleanField(default=False, verbose_name='웹 푸시 사용')),
                ('kakao_enabled', models.BooleanField(default=False, verbose_name='카카오톡 사용')),
                ('reminder_enabled', models.BooleanField(default=False, verbose_name='미확인 재알림 사용')),
                ('is_active', models.BooleanField(default=True, verbose_name='알림 계정 활성')),
                ('last_notification_connected_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 알림 연결 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_profile', to=settings.AUTH_USER_MODEL, verbose_name='로그인 계정')),
            ],
            options={
                'verbose_name': '직원 알림 설정',
                'verbose_name_plural': '직원 알림 관리',
                'ordering': ['display_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True, verbose_name='푸시 전송 주소')),
                ('p256dh', models.TextField(verbose_name='기기 공개키')),
                ('auth', models.TextField(verbose_name='기기 인증키')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='기기 이름')),
                ('browser', models.CharField(blank=True, max_length=80, verbose_name='브라우저')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 연결 시각')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='해제 시각')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='staff_notifications.staffnotificationprofile', verbose_name='직원')),
            ],
            options={
                'verbose_name': '웹 푸시 기기',
                'verbose_name_plural': '웹 푸시 등록 기기',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web_push', '웹 푸시'), ('kakao', '카카오톡')], max_length=20, verbose_name='알림 채널')),
                ('kind', models.CharField(choices=[('initial', '신규 상담'), ('reminder', '미확인 재알림'), ('test', '시험 알림')], max_length=20, verbose_name='알림 종류')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='재알림 순번')),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리 중'), ('retry', '재시도 대기'), ('sent', '발송 완료'), ('failed', '발송 실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('idempotency_key', models.CharField(max_length=160, unique=True, verbose_name='중복 방지 키')),
                ('safe_payload', models.JSONField(blank=True, default=dict, verbose_name='최소 알림 내용')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='발송 예정 시각')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='작업 시작 시각')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 완료 시각')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='시도 횟수')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='최대 시도 횟수')),
                ('last_error_code', models.CharField(blank=True, max_length=80, verbose_name='최근 오류 코드')),
                ('last_error_message', models.CharField(blank=True, max_length=200, verbose_name='최근 오류 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='consultations.consultation', verbose_name='상담')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='staff_notifications.staffnotificationprofile', verbose_name='수신 직원')),
            ],
            options={
                'verbose_name': '알림 작업',
                'verbose_name_plural': '알림 작업 현황',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KakaoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='카카오 회원번호')),
                ('access_token_encrypted', models.TextField(blank=True, verbose_name='암호화 액세스 토큰')),
                ('refresh_token_encrypted', models.TextField(blank=True, verbose_name='암호화 리프레시 토큰')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='액세스 토큰 만료')),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='리프레시 토큰 만료')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='연결 시각')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 갱신 시각')),
                ('is_active', models.BooleanField(default=False, verbose_name='연결 사용')),
                ('reconnect_required', models.BooleanField(default=False, verbose_name='재연결 필요')),
                ('last_error_code', models.CharField(blank=True, max_length=80, verbose_name='최근 오류 코드')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kakao_connection', to='staff_notifications.staffnotificationprofile', verbose_name='직원')),
            ],
            options={
                'verbose_name': '카카오톡 연결',
                'verbose_name_plural': '카카오톡 연결 상태',
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', '성공'), ('failed', '실패'), ('expired', '구독 만료'), ('skipped', '건너뜀')], max_length=20, verbose_name='결과')),
                ('response_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='응답 코드')),
                ('error_code', models.CharField(blank=True, max_length=80, verbose_name='오류 코드')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='오류 요약')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='시도 시각')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='staff_notifications.notificationjob', verbose_name='알림 작업')),
                ('push_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='staff_notifications.pushsubscription', verbose_name='푸시 기기')),
            ],
            options={
                'verbose_name': '알림 발송 기록',
                'verbose_name_plural': '알림 발송 기록',
                'ordering': ['-attempted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('push_subscription__isnull', False), ('status', 'sent')), fields=('job', 'push_subscription'), name='unique_successful_push_delivery')],
            },
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['profile', 'is_active'], name='push_profile_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['status', 'scheduled_at'], name='notify_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationjob',
            index=models.Index(fields=['consultation', 'kind'], name='notify_consult_kind_idx'),
        ),
    ]
