# Generated by Django 5.2.16 on 2026-07-22

import django.core.validators
import django.db.models.deletion
import staff_resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="StaffResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("guide", "업무 안내"), ("training", "직원 교육"), ("form", "서식·자료"), ("video", "영상 자료")], max_length=20, verbose_name="분류")),
                ("title", models.CharField(max_length=150, verbose_name="자료명")),
                ("slug", models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True, verbose_name="자료 주소")),
                ("summary", models.CharField(max_length=240, verbose_name="짧은 설명")),
                ("body", models.TextField(blank=True, verbose_name="상세 안내")),
                ("attachment", models.FileField(blank=True, help_text="PDF, 한글, Word, Excel, PowerPoint, 이미지 또는 ZIP 파일을 8MB 이하로 등록해 주세요.", upload_to=staff_resources.models.resource_file_path, validators=[django.core.validators.FileExtensionValidator(["pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "hwp", "hwpx", "jpg", "jpeg", "png", "webp", "zip"]), staff_resources.models.validate_resource_size], verbose_name="첨부파일")),
                ("external_url", models.URLField(blank=True, help_text="내부 자료에 필요한 외부 링크가 있을 때만 입력해 주세요. 민감한 자료는 외부 서비스에 올리지 마세요.", verbose_name="관련 링크")),
                ("is_published", models.BooleanField(default=False, verbose_name="직원에게 공개")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="공개 시각")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="등록 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 시각")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_staff_resources", to=settings.AUTH_USER_MODEL, verbose_name="등록자")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_staff_resources", to=settings.AUTH_USER_MODEL, verbose_name="마지막 수정자")),
            ],
            options={
                "verbose_name": "직원 자료",
                "verbose_name_plural": "직원 자료",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
